### ISSUE TITLE
An exception occurred retrieving your Google's accounts ClientLogin token: undefined method `message' for #<String:0x25062c0>

### ISSUE THREAD

**Issue by darkzbaron** [flebel/downloadGoogleContacts.rb#1]
Bonjour, trying to run this but this is the message i am getting. 
running Ruby 1.8.7

Any help?

Jonathan

**Comment by flebel** [comment]
Hi Jonathan,

This project has not been updated in almost 9 years and myself I have not used it in years. If you would still like to troubleshoot this issue, may I suggest you change `#{e.message}` to `#{e}` on line 207 to see the actual error message: https://github.com/flebel/downloadGoogleContacts.rb/blob/b6d82e23376c178c371480e41cf4857d1057751c/downloadGoogleContacts.rb#L207

Best,
Francois

**Comment by darkzbaron** [comment]
Hi Francois, thanks so much for your quick answer. Really appreciate. Here is the "full" debug.
 ```
Attempting to download a new ClientLogin Authentication Token...
An exception occurred retrieving your Google's accounts ClientLogin token: undefined method `message' for #<String:0xa0cebd0>
A new ClientLogin Token has been saved to token
Attempting to download your Google Contacts Atom feed...
There was a problem with the Client Login Authentication Token: Token invalid
An exception occurred retrieving your Google Contacts: wrong number of arguments (1 for 0)
```
I get this running the following command:
"downloadGoogleContacts.rb" -v -e myemail -p mypassword -t "token" -o "output" -m 10 -v

**Comment by darkzbaron** [comment]
in the meantime i found a git doing the same thing. https://gitlab.com/goobook/goobook/tree/master
I would however, gladly have your help in getting this to one to work - https://github.com/flebel/cisco79xx_phone_directory

I will upload the logs on the page
